bch_bindgen: use bitfield_enum() for flags enums
It is illegal (UB) to transmute arbitrary integers into Rust enums,
and this causes panics in debug builds:

--- 8< ---
'main' (156945) panicked at bch_bindgen/src/btree/mod.rs:62:46:
trying to construct an enum from an invalid value 0x0
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_nounwind_fmt
   2: core::panicking::panic_invalid_enum_construction
   3: <bch_bindgen::btree::BtreeTrans>::commit
             at /home/intelfx/devel/ext/bcachefs-tools/bch_bindgen/src/btree/mod.rs:62:46
   4: bch_bindgen::btree::commit_do::<bcachefs::copy_fs::create_or_update_file::{closure#0}>::{closure#0}
             at /home/intelfx/devel/ext/bcachefs-tools/bch_bindgen/src/btree/mod.rs:133:15
   5: bch_bindgen::btree::lockrestart_do::<(), bch_bindgen::btree::commit_do<bcachefs::copy_fs::create_or_update_file::{closure#0}>::{closure#0}>
             at /home/intelfx/devel/ext/bcachefs-tools/bch_bindgen/src/btree/mod.rs:106:15
   6: bch_bindgen::btree::commit_do::<bcachefs::copy_fs::create_or_update_file::{closure#0}>
             at /home/intelfx/devel/ext/bcachefs-tools/bch_bindgen/src/btree/mod.rs:131:5
   7: bch_bindgen::btree::trans_commit_do::<bcachefs::copy_fs::create_or_update_file::{closure#0}>
             at /home/intelfx/devel/ext/bcachefs-tools/bch_bindgen/src/btree/mod.rs:151:5
   8: bcachefs::copy_fs::create_or_update_file
             at /home/intelfx/devel/ext/bcachefs-tools/src/copy_fs.rs:307:9
   9: bcachefs::copy_fs::copy_dir
             at /home/intelfx/devel/ext/bcachefs-tools/src/copy_fs.rs:978:25
  10: bcachefs::copy_fs::copy_fs
             at /home/intelfx/devel/ext/bcachefs-tools/src/copy_fs.rs:1100:5
  11: bcachefs::commands::image::image_create_inner::{closure#6}
             at /home/intelfx/devel/ext/bcachefs-tools/src/commands/image.rs:572:9
  12: bcachefs::commands::image::image_create_inner
             at /home/intelfx/devel/ext/bcachefs-tools/src/commands/image.rs:570:18
  13: bcachefs::commands::image::cmd_image_create
             at /home/intelfx/devel/ext/bcachefs-tools/src/commands/image.rs:1038:18
  14: bcachefs::main
             at /home/intelfx/devel/ext/bcachefs-tools/src/bcachefs.rs:380:31
  15: <fn() -> std::process::ExitCode as core::ops::function::FnOnce<()>>::call_once
             at /usr/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
--- 8< ---