bcachefs: Add statement to switch in check_bch_counter_ids_unique()
Clang warns (or errors with CONFIG_WERROR=y):

  fs/bcachefs/sb-counters_format.h:132:2: error: label at end of compound statement is a C23 extension [-Werror,-Wc23-extensions]
    132 |         }
        |         ^

In older versions of clang, this is an unconditional hard error:

  fs/bcachefs/sb-counters_format.h:130:34: error: label at end of compound statement: expected statement
          BCH_PERSISTENT_COUNTERS()
                                   ^
                                    ;

Add an empty statement to resolve the error/warning.

Fixes: 38de86383436 ("bcachefs: Switch statement evaluate ids and confirm they are unique going forward")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>